export { default as logo } from './logo.png' 
export { default as emblem } from './emblem.png' 
export { default as background } from './background.png' 
export { default as mapImage } from './mapImage.png' 
export { default as searchIcon } from './searchIcon.png' 
export { default as example } from './example.png'