export { default as black } from './black.png' 
export { default as blue } from './blue.png' 
export { default as purple } from './fiol.png' 
export { default as green } from './green.png' 
export { default as simple } from './map-marker-icon.png' 
export { default as orange } from './orange.png'
export { default as pink } from './pink.png'
export { default as lightBlue } from './рр.png'
export { default as myLoc} from './myLoc.png'
